version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    expose:
      - "3000"
    environment:
      - REACT_APP_API_URL=http://localhost/api
    networks:
      - app-network
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.production
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
      - PORT=8000
      - CORS_ORIGINS=http://localhost,http://127.0.0.1
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/data:/app/data
      - ./backend/models:/app/models
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge