# Backend configuration
app = "wage-prediction-backend"
primary_region = "sjc"

[build]
  dockerfile = "backend/Dockerfile"

[env]
  PORT = "8000"

[mounts]
  source = "ml_models"
  destination = "/app/data"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = 2000

---

# Frontend configuration
app = "wage-prediction-frontend"
primary_region = "sjc"

[build]
  dockerfile = "frontend/Dockerfile"

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    port = 80