services:
  # Backend service
  - type: web
    name: wage-prediction-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    rootDir: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
    disk:
      name: ml-models
      mountPath: /app/data
      sizeGB: 1

  # Frontend service
  - type: web
    name: wage-prediction-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: ./frontend/build
    rootDir: .
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: wage-prediction-backend
          property: host