services:
  - type: web
    name: sambiowage-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python run.py"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        value: https://sambiowage.vercel.app,http://localhost:3000
    autoDeploy: false